-- =====================================================================
-- TCA <-> Nexus Linker — Supabase schema (lightweight name-based identity)
-- Run this once in your Supabase project: SQL Editor -> New query -> paste -> Run.
--
-- No authentication: each expert just types a display name (stored in their
-- browser). Access uses the public anon key, so anyone with the app URL can
-- read/write. Fine for a trusted expert exercise; add Auth later if needed.
-- =====================================================================

-- Drop old auth-based tables if they exist (safe: no real data yet).
drop table if exists public.links cascade;
drop table if exists public.experts cascade;

-- ---- Tables ----------------------------------------------------------

-- Expert profile. id is generated by the client (a stable browser UUID).
create table public.experts (
  id         uuid primary key,
  name       text not null,
  created_at timestamptz not null default now()
);

-- One row = one expert linking one (TCA action, Nexus option) pair with a force.
create table public.links (
  id              uuid primary key default gen_random_uuid(),
  expert_id       uuid not null references public.experts (id) on delete cascade,
  tca_action_id   text not null,                 -- e.g. 'TCA5-A01'
  nexus_option_id text not null,                 -- e.g. Nexus code 'B01'
  strength        text not null check (strength in ('primary', 'secondary')),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (expert_id, tca_action_id, nexus_option_id)
);

create index links_tca_idx   on public.links (tca_action_id);
create index links_nexus_idx on public.links (nexus_option_id);

-- ---- Row Level Security (permissive: anon may read/write) ------------

alter table public.experts enable row level security;
alter table public.links   enable row level security;

drop policy if exists "experts_all" on public.experts;
drop policy if exists "links_all"   on public.links;
create policy "experts_all" on public.experts for all to anon, authenticated using (true) with check (true);
create policy "links_all"   on public.links   for all to anon, authenticated using (true) with check (true);

-- ---- Realtime (live agreement updates across experts) ----------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'links'
  ) then
    alter publication supabase_realtime add table public.links;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'experts'
  ) then
    alter publication supabase_realtime add table public.experts;
  end if;
end $$;
